config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/auth/:provider/callback' => 'application#authentication_callback'
  get '/logout' => 'application#logout', as: 'logout'
  get '/refresh_token' => 'home#refresh_token', as: 'refresh_token'
  resources :items, only: [:index]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authentication_callback
    auth = request.env['omniauth.auth']
    reset_session

    if auth.uid
      credential = auth.credentials
      session[:id] = auth.uid
      session[:email] = auth.info.email
      session[:full_name] = auth.info.full_name
      session[:business_id] = auth.info.business_id
      session[:outlet_ids] = auth.info.outlet_ids
      session[:logged] = true
      session[:access_token] = credential.token
      session[:refresh_token] = credential.refresh_token
      session[:expires_at] = credential.expires_at
      redirect_to root_path, logout: true
    end
  end

  def logout
    auth = nil
    reset_session
    render "home/index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def refresh_token
    refresh_token = session[:refresh_token]
    uri = URI("#{ENV['MOKA_HOST_PROVIDER']}/oauth/token")
    res = Net::HTTP.post_form(uri, 'grant_type' => 'refresh_token', 'client_id' => ENV['MOKA_APP_ID'], 'client_secret' => ENV['MOKA_SECRET_KEY'], 'refresh_token' => refresh_token)
    new_credential = JSON.parse(res.body)
    session[:access_token] = new_credential["access_token"]
    session[:refresh_token] = new_credential["refresh_token"]
    session[:expires_at] = new_credential["expires_at"]
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    res = get_items

    if !res.is_a?(Net::HTTPSuccess)
      refresh_token = session[:refresh_token]
      uri = URI("#{ENV['MOKA_HOST_PROVIDER']}/oauth/token")
      res = Net::HTTP.post_form(uri, 'grant_type' => 'refresh_token', 'client_id' => ENV['MOKA_APP_ID'], 'client_secret' => ENV['MOKA_SECRET_KEY'], 'refresh_token' => refresh_token)
      new_credential = JSON.parse(res.body)
      session[:access_token] = new_credential["access_token"]
      session[:refresh_token] = new_credential["refresh_token"]
      session[:expires_at] = new_credential["expires_in"]
      res = get_items
    end

    render json: res.body
  end

  def get_items
    uri = URI("#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/items")
    params = {access_token: session[:access_token]}
    uri.query = URI.encode_www_form(params)
    Net::HTTP.get_response(uri)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if session[:logged] %>
  <h3>Selamat Datang <%= session[:full_name] %></h3>
  <%= link_to 'Logout', logout_path %>
  <br/> <br/>
  <br/>
  access_token: <%= session[:access_token] %>
  <br/>
  refresh_token: <%= session[:refresh_token] %>
  <br/>
  business_id: <%= session[:business_id] %>
  <br/>
  outlet_ids: <%= session[:outlet_ids] %>
  <br/> <br/> <br/>
  <h2>Sample URL</h2>
  Library
  <ul>
    <li><%= link_to 'Business', "#{ENV['MOKA_HOST_PROVIDER']}/v1/businesses?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Outlets', "#{ENV['MOKA_HOST_PROVIDER']}/v1/businesses/#{session[:business_id]}/outlets?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Item Library', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/items?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Categories', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/categories?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Modifiers', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/modifiers?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Discounts', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/discounts?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Taxes', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/taxes?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Gratuities', "#{ENV['MOKA_HOST_PROVIDER']}/v1/outlets/#{session[:outlet_ids].first}/gratuities?access_token=#{session[:access_token]}", target: '_blank' %></li>
  </ul>
  Reports
  <ul>
    <li><%= link_to 'Sales Summary', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/sales_summary?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Payment Methods', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/payment_methods?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Item Sales', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/item_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Category Sales', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/category_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Modifier Sales', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/modifier_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Discounts', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/discount_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Taxes', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/tax_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Gratuities', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/gratuity_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Collected By', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/collector_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Served By', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/server_sales?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Transactions', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/transactions?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Get Latests Transactions', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/get_latest_transactions?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Invoices', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/invoices?access_token=#{session[:access_token]}", target: '_blank' %></li>
    <li><%= link_to 'Shifts', "#{ENV['MOKA_HOST_PROVIDER']}/v2/outlets/#{session[:outlet_ids].first}/reports/shifts?access_token=#{session[:access_token]}", target: '_blank' %></li>
  </ul>
  Customers
  <ul>
    <li><%= link_to 'Customers', "#{ENV['MOKA_HOST_PROVIDER']}/v1/businesses/#{session[:business_id]}/customers?mobile_device=true&access_token=#{session[:access_token]}", target: '_blank' %></li>
  </ul>
  Sample Refresh Token
  <ul>
    <li><%= link_to 'Only Refresh Token', refresh_token_path %></li>
    <li><%= link_to 'Items With Refresh Token', items_path, target: '_blank' %></li>
  </ul>
  Info Token
  <ul>
    <li><%= link_to 'Token Info', "#{ENV['MOKA_HOST_PROVIDER']}/oauth/token/info?access_token=#{session[:access_token]}", target: '_blank' %></li>
  </ul>
<% else %>
  <div class="button">
    <a href="<%= root_url %>auth/moka" class="btn-login-with-moka">
      Login With Moka
    </a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MOKA API Client</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>